feat: Replace fetchAppLatestVersion by fetchAppVersion
cozy/cozy-client pull request #1002
Opened 2021-08-12 13:44 UTC by doubleface

The stack's registry API also allow to get a specific version of an app
and this is needed by the amiral app.

This is a breaking change since the fetchAppLatestVersion won't exist
anymore, but it is not used yet. I think it is safe to replace it now.- feat: Replace fetchAppLatestVersion by fetchAppVersion

2021-08-12 14:13 UTC, Crash-- requested changes
You should add a BREAKING CHANGE: message in the commit in order to create a new major version and to explain how to migrate. 

We're not alone using CozyClient :)

2021-08-12 16:34 UTC, doubleface commented
@Crash-- Done

2021-08-13 07:02 UTC, Crash-- approved these changes

2021-08-13 07:16 UTC, JF-Cozy approved these changes

2021-08-13 07:57 UTC, Crash-- commented
nit: one way to not create a BC can be : 

fetchAppLatestVersion(app){
return fetchAppVersion(app, 'latest')
}

2021-08-13 14:45 UTC, merged