feat: Include_docs is done by default by fetchChanges
cozy/cozy-client pull request #967
Opened 2021-06-17 07:13 UTC by ptbrowne

Fetch changes needs to have the docs included in the changes response
since it filters null documents, deleted documents, and design docs.
With include_docs: false, fetchChanges was not functional, thus it makes
no sense to support it. Now, the caller of fetchChanges doesn't need to
pass include_docs: true, it is set automatically by
DocumentCollection::fetchChanges

2021-06-17 07:41 UTC, JF-Cozy approved these changes

2021-06-17 07:43 UTC, Crash-- requested changes
I don't know what to think about this fix yet. 

include_docs false is the default behavior of CouchDB. https://docs.couchdb.org/en/stable/api/database/changes.html 

Also, if we set it to true by default, we should be able to override it by setting it to false. It seems not possible in this PR ATM. 

@paultranvan do you have an opinion about this change?

2021-06-17 07:48 UTC, ptbrowne commented
I agree with you that include_docs should be settable to false. The thing is that right now, fetchChanges has a bigger scope that CouchDB fetchChanges since it deals with deleted documents, design docs, etc... If include_docs could be set to false, it would be incompatible with the other options. I could stir the PR in this sense, making it possible to set it as false and removing the filters that need to have docs.

2021-06-17 08:57 UTC, paultranvan commented
I agree that include_docs should be settable to false, as I does make sense to query the `_changes` to only retrieve changed doc ids, just like the default behaviour of this API. 

> I could stir the PR in this sense, making it possible to set it as false and removing the filters that need to have docs.

It seems good to me :) 

About the default value of `include_docs`, I generally tend to prefer to respect the CouchDB's defaults, but I think it's also ok to set it to true if it's our default usage of the API, and avoid bugs such as the one referenced by @ptbrowne

2021-06-17 09:41 UTC, ptbrowne commented
I tried an implementation in https://github.com/cozy/cozy-client/pull/967/commits/4f314a5eb4d2ef713aec453ceffad2ae5ee7b76a but I do not think it is the way to go. Here fetchChanges is already too high level and I do not think we should try to accomodate the low level include_docs in it. You can see in the implementation that if we do have include_docs set to false, we are forced to send back the complete `results`. Hence the shape of the return value is different if include_docs is set to false or true.

```
true: { docs, newSeq }
false: { results, newSeq }
```

I think to accomodate the need to have low level access to _changes params and keep the existing fetchChanges, instead of including the possibility to  set include_docs to false into fetchChanges, we could have another method `fetchChangesRaw` that would be 1-1 with _changes (thus you could call it with include_docs: false). And fetchChanges would stay at a higher level, with include_docs set to true (and not settable to false), and with the responsibility to filter design docs and deleted documents.

2021-06-17 12:45 UTC, paultranvan commented
@ptbrowne Ok, `fetchChangesRaw` looks like a good idea :+1: 
On a side note, I think it's kind of a pity to return docs as `documents`, while we already have `data`, `docs` or `rows` depending on the API (but I assume this is an old design choice)

2021-06-18 06:22 UTC, Crash-- reviewed
I like the idea of the `fetchChangesRaw` method. 

So `fetchChanges` to be "high level" for an application, `fetchChangesRaw` if we want to be as close as possible to the Couch API. 👍

2021-06-18 06:22 UTC, Crash-- commented on packages/cozy-client/types/types.d.ts
> +export type QueryFetchStatus = "loading" | "loaded" | "pending" | "failed";
the come back!

2021-07-01 05:59 UTC, Crash-- approved these changes

2021-07-01 06:27 UTC, merged